[project]
name = "trunco-workspace"
version = "0.1.0"
description = "Monorepo workspace for Trunco packages."
authors = [
    { name = "Ali Tavallaie", email = "a.tavallaie@gmail.com" }
]



[tool.uv.workspace]
members = [
    "packages/trunco-core",
    "packages/trunco-franken",
    "packages/pychart"]

[tool.uv.sources]
trunco-core = { workspace = true }
trunco-franken = { workspace = true }

[build-system]
requires = ["uv>=0.6.0"]
build-backend = "uv.build_backend"
